version: "3"
services:
  ipfs:
    image: ipfs/go-ipfs:latest
    volumes:
    - "./export:/export"
    - "./data/ipfs:/data/ipfs"
    ports:
    - "5001:5001"
    - "4001:4001"
    - "8080:8080"
  app:
    build: .
    ports:
    - "3000:3000"
    links:
    - ipfs  